services:
  # MongoDB for Projects Service
  mongo-projects:
    image: mongo:6.0
    container_name: mongo-projects
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27018:27017"
    volumes:
      - projects-mongo-data:/data/db
    networks:
      - projects-network

  # Flask Projects Service
  projects-service:
    build: .
    container_name: projects-service
    depends_on:
      - mongo-projects
    environment:
      PORT: ${PORT}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      MONGO_HOST: mongo-projects
      MONGO_PORT: ${MONGO_PORT}
      MONGO_DB: ${MONGO_DB}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_AUTHSOURCE: ${MONGO_AUTHSOURCE}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - "${PORT}:${PORT}"
    networks:
      - projects-network

volumes:
  projects-mongo-data:

networks:
  projects-network:
    driver: bridge

